language: ruby
rvm:
- 2.5.3
sudo: false
before_install:
- gem install bundler -v 1.17.1
- openssl aes-256-cbc -K $encrypted_3fcaa4ab4463_key -iv $encrypted_3fcaa4ab4463_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
install:
- bundle install
script:
- RAILS_ENV=test bundle exec rake db:create db:migrate
- bundle exec rake db:test:prepare
- bundle exec rake spec:travis