entrypoint: bundle exec rackup --port $PORT
env: flex
runtime: ruby
env_variables:
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: u2xrMBSMvssv
  DATABASE_NAME: works_with_postgresql
  DATABASE_HOST: 35.245.10.148
  SECRET_KEY_BASE: 520ecbda225951aab900323dee4ddcd97491dae9ea632e44e52afc4fc1c179ec47633b9cf8218dd989800bfced73c4ed7af4df7834766d8d5aaed25c691efbd7
  GCLOUD_BUCKET: works-with-image-upload
  GOOGLE_CLIENT_EMAIL: works-with-photouploader@works-with-222514.iam.gserviceaccount.com
  GOOGLE_JSON_KEY: https://00e9e64bacdf19ce18e0b793d90c593d1d19717208ed01e242-apidata.googleusercontent.com/download/storage/v1/b/works-with-credentials/o/.gcp-keyfile.json?qk=AD5uMEuepVl2UHuP39ZwNpJy1KKZK2vwUEUGxYTxGnVx_rzfy3nm-HJm5MutjQQArC3zLaCVDzmlzmQFdZiwA1ox6AArYvWnT5ul0CMpHr3r6kE45nc3OcQvAERePhirFtqPFL2cN6sPcAFNFQNO95rhsAQv2DxqWaCss0er9Wd-vcAhIJFIEH_KssuuUNrfXU1TvuB8zpaCLcMDoJGOvv_s8vwWcOzy47IArWBmszcjiSU4Wh9F18rlGR3JxusrPflLqOSdAk4MMyeRDZQOpptdmwgIXOG7OTlnqFlvucLUa2jUSu5FqYZWwwD5k6aLoQ5gKzas4Zefuzlg1vGbIS5QiglzYV8hlEBjknqOjupT2NTEt6VhmMlP6SfIu6DU8vRO0EPpBfwtB7dEF5lQVXJ6-xGdtnYeFuBSs_Mkv4pmMXam6cWpeSYZ3lw9GZBM4BnJvbT_GgXMk_ejjKelWFBgQsbl7JEQB0ju3Lb6-HF1MkaJTWnSQWF7Yfzj3GAkQEqCgPYDIYA6sj-V4dZgF0uszBIrbT8TRpdl-3MaRbP1hUX5XbglvCm-hjzvz5HuFL-dJXQAttR7zPZyW-7xNIExm6qUS2golxbGrF1GvUybQ4_iAiIMDJdchHNppWtvpbhazwV_4FX6qT2aWWj11_MCYaqyrBC3K3kyQPwpM8VDVGFoT5vQbu8aSnMyJ_KMnVmgtwcSyUkgzkhS45nQsqtVnvIZBYMhL4a_pBeX-rXQ1d5YozeOrHretVBdPtbio3rAy6__Ei8MSg_qYBmuE0WG4FUGzJuM0Q
  GOOGLE_STORAGE_ACCESS_KEY_ID: GOOGZPQTHMUX23LNHTHTUUBZ
  GOOGLE_STORAGE_SECRET_ACCESS_KEY: BZWAPgIMqoTryTao682ESIhRyq4JTUOfFUasmYRH
