version: '3'
services:
  bundler:
    build: .
    command: gem install bundler -v  2.0.0.pre.1
    volumes:
      - .:/msk-works-with
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/msk-works-with
    ports:
      - "3000:3000"
    links:
      - bundler
    depends_on:
      - bundler