default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

postgresql_settings: &postgresql_settings
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  password: u2xrMBSMvssv
  host:   35.245.10.148
  database: works_with_postgresql

development:
  <<: *default
  database: works_with_development
  user: postgres
  password: amops

test:
  <<: *default
  database: works_with_test
  user: postgres
  password: amops

production:
  <<: *postgresql_settings